#! /usr/bin/env bash

export WIPE_DATA="NO"
export DATA=${DATA:-${DATAROOT}/${RUN}atmensanl_${cyc}}
source "${HOMEgfs}/ush/jjob_header.sh" -e "atmensanlfinal" -c "base atmensanl atmensanlfinal"

##############################################
# Set variables used in the script
##############################################
GDUMP="gdas"
GDUMP_ENS="enkf${GDUMP}"
GDATE=$(${NDATE} -"${assim_freq}" "${PDY}${cyc}")
# shellcheck disable=
export gPDY=${GDATE:0:8}
export gcyc=${GDATE:8:2}

. "${HOMEgfs}/ush/load_ufsda_modules.sh"
##############################################
# Begin JOB SPECIFIC work
##############################################
# Generate COM variable from template
MEMDIR='ensstat' RUN=${GDUMP_ENS} YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
    COMOUT_ATMOS_ANALYSIS_ENS:COM_ATMOS_ANALYSIS_TMPL

mkdir -m 755 -p "${COMOUT_ATMOS_ANALYSIS_ENS}"

MEMDIR='ensstat' RUN=${GDUMP_ENS} YMD=${gPDY} HH=${gcyc} declare_from_tmpl -rx \
    COM_ATMOS_ANALYSIS_ENS_PREV:COM_ATMOS_ANALYSIS_TMPL

###############################################################
# Run relevant script

EXSCRIPT=${GDASATMENSFINALPY:-${SCRgfs}/exglobal_atmens_analysis_finalize.py}
${EXSCRIPT} && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

cp ${COM_ATMOS_ANALYSIS_ENS_PREV}/gdas.t${gcyc}z.rad_varbc_params.tar ${COM_ATMOS_ANALYSIS_ENS}/gdas.t${cyc}z.rad_varbc_params.tar
cp ${COM_ATMOS_ANALYSIS_ENS_PREV}/gdas.t${gcyc}z.atms_n20.satbias.nc ${COM_ATMOS_ANALYSIS_ENS}/gdas.t${cyc}z.atms_n20.satbias.nc
cp ${COM_ATMOS_ANALYSIS_ENS_PREV}/gdas.t${gcyc}z.atms_n20.satbias_cov.nc ${COM_ATMOS_ANALYSIS_ENS}/gdas.t${cyc}z.atms_n20.satbias_cov.nc
cp ${COM_ATMOS_ANALYSIS_ENS_PREV}/gdas.t${gcyc}z.atms_n20.tlapse.txt ${COM_ATMOS_ANALYSIS_ENS}/gdas.t${cyc}z.atms_n20.tlapse.txt


##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]] ; then
  cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" && true
export err=$?
set +e
if [[ ${err} -ne 0 ]]; then
    err_exit "${DATAROOT} does not exist, ABORT!"
fi
set_trace
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
