#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"

if (( 10#${ENSMEM:-0} > 0 )); then
  export DATAjob="${DATAROOT}/${RUN}efcs${ENSMEM}.${PDY:-}${cyc}"
  export DATA="${DATAjob}/${jobid}"
  source "${HOMEgfs}/ush/jjob_header.sh" -e "efcs" -c "base fcst efcs"
else
  export DATAjob="${DATAROOT}/${RUN}fcst.${PDY:-}${cyc}"
  export DATA="${DATAjob}/${jobid}"
  source "${HOMEgfs}/ush/jjob_header.sh" -e "fcst" -c "base fcst"
fi

# Create the directory to hold restarts and output from the model in stmp
export DATArestart="${DATAjob}/restart"
if [[ ! -d "${DATArestart}" ]]; then mkdir -p "${DATArestart}"; fi
export DATAoutput="${DATAjob}/output"
if [[ ! -d "${DATAoutput}" ]]; then mkdir -p "${DATAoutput}"; fi

##############################################
# Begin JOB SPECIFIC work
##############################################


###############################################################
# Run relevant exglobal script
###############################################################
#"${FORECASTSH:-${SCRgfs}/exjedi_inline.py}"
python "${FORECASTSH:-${SCRgfs}/exjedi_inline.py}"
status=$?
(( status != 0 )) && exit "${status}"

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]] ; then
  cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
#cd "${DATAROOT}" || true
## do not remove DATAjob. It contains DATAoutput
#if [[ "${KEEPDATA}" == "NO" ]]; then
#  rm -rf "${DATA}"
#
#  # Determine if this is the last segment
#  commas="${FCST_SEGMENTS//[^,]}"
#  n_segs=${#commas}
#  if (( n_segs - 1 == ${FCST_SEGMENT:-0} )); then
#    # Only delete temporary restarts if it is the last segment
#    rm -rf "${DATArestart}"
#  fi
#fi

exit 0
